export const TYPES = {
    GETPOST: "GETPOST",
    USERLOGIN: "USERLOGIN",
    ADMINLOGIN: "ADMINLOGIN",
    LOGOUT: "LOGOUT",
    WRONGCRED: "WRONGCRED",
    GETCOMMENT: "GETCOMMENT",
    DELETECOMMENT: "DELETECOMMENT",
    EDITCOMMENT: "EDITCOMMENT",
    DELETEPOST: "DELETEPOST",
    EDITPOST: "EDITPOST",
    LOADING: "LOADING",
    STOPLOADING: "STOPLOADING",
}